name: Build Windows Executable

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nuitka
      run: pip install nuitka

    - name: Compile Python script
      run: nuitka3 --standalone --onefile --output-dir=dist downloader.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: downloader-exe
        path: dist/downloader.exe


