name: Build Windows Executable

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nuitka
      run: pip install nuitka

    - name: Compile Python script
      run: nuitka --standalone --onefile --output-dir=build/downloader downloader.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: downloader.exe
        path: build/downloader/downloader.exe

